travis:
  secure:
    BINSTAR_TOKEN: L/O+eJoWa36fZ3fex2d2M8lWWVuYm6idfQ52bzCdWJ3XdzgUijyTShBzKFV48SebYN0lo4NCglrkOSMtLTLfwWlJFThXyngl2jfQs0Oo4pbqNTPIHoYaTUy/auS7K0UbSIXlQ7TOzJaWKhd+N0DRH9DaAeEncpdlzHBz5c3HS4+J/YovNfgpC516Zl2GfSMRNaKjDhwpmsDoZs7Ec98lSVZVMjIkyxnIqS8Bgd+edjvjEWoZzbLKv9o/UyxOFiEo4a0iF4LeyghKSEMUlorympSDnQCGkR524Vm6yetn2oXsfeynV9joxoFwWbUCvZHMMADxb0/gt+loJKHOEJbMe8s4vVO56TH8iEBjY8VSToAsiUEMXSm30n02Vg39i6UU9B8HUwonr6k5zH/mj6kxd0caEMLoFYvthVDrBoqsvy4CJMlayUwZ/26JVNuPPGDA2N25BRXphvn4PSdbYE5UUEC6MBDWjMhQR21o0hGgDsHYJzbPEY1dkqp8XvNUwS+BD/C5olKCeMVCFKyZw7pwOiYHjHh31j43VsdbH4StS3W493uzObZt5ab0U21294KDRfw3ek5bVYSdFQdluI05H5QZe0jGTpWjNbQj6LfnFhJiM+F+cGqBdFNozIA/3UkLL5wi4CvYAL1wdcera964/KLxrs/1yQvrsubxwkppypQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
